Update "TodoMVC" example to Relay 0.9.1
Tested with:

```
cd TodoMVC
rm -r node_modules/*
npm install # see no warning about peer deps
npm run update-schema
npm start
rm -r ios/build/*
react-native run-ios
```

Note there is a kludgy workaround in here to get `react-native run-ios` to run.
The `source-map` package has a dependency on `amdefine` in its package.json, but
we're blowing up at runtime as follows:

```
Error: Cannot find module 'amdefine'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> ($REDACTED/relay-examples/TodoMVC/node_modules/react-native/node_modules/source-map/lib/source-map/source-map-generator.js:8:18)
    at Module._compile (module.js:413:34)
    at Module._extensions..js (module.js:422:10)
    at Object.require.extensions.(anonymous function) [as .js] ($REDACTED/relay-examples/TodoMVC/node_modules/babel-register/lib/node.js:166:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

unless I add it to the top-level package.json. I'll see if I can find the root
cause, but in the meantime just want to unbreak the example.